server.port: ${PORT:8081}

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer


  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9092}

    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: yt.
      properties:
        enable.idempotence: true

    consumer:
      isolation-level: read_committed
      enable-auto-commit: false

redis:
  host: ${REDIS_HOSTNAME:localhost}
  port: ${REDIS_PORT:6379}

app.jwt.secret: 0793wvjzTy9ckZgtNGg6z7NJOw7uN4/bdslDkWLhh/E7SrIqyhuJBbzhWfiL9X0dHn1LIG6FoUyGDBZV1DYW0w9nEh7oLCdhmKCAR6dSc5fjLtCrs2br44kzF8hOtz4V
